name: Build C++ UDP Forwarder for Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Compile C++ code
      # 使用静态链接运行时库，确保可移植性
      run: cl.exe forwarder_punch.cpp /std:c++17 /EHsc /O2 /MT /Fe:udp_forwarder.exe /link Ws2_32.lib Shlwapi.lib

    - name: Prepare artifact for upload
      run: |
        mkdir release
        copy udp_forwarder.exe release\
        copy config.ini release\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: udp-forwarder-windows
        path: release/
