name: Build C++ UDP Forwarder for Windows (using MinGW)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MinGW-w64
      # 使用这个 action 来安装 GCC 编译器
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile C++ code with GCC
      # 使用 g++ 编译器，并包含对 GCC 至关重要的 -pthread 参数
      run: g++ -std=c++17 -o udp_forwarder.exe forwarder_punch.cpp -lws2_32 -lshlwapi -static -pthread
      shell: bash

    - name: Prepare artifact for upload
      run: |
        mkdir release
        cp udp_forwarder.exe release/
        cp config.ini release/
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: udp-forwarder-windows
        path: release/
